### PR TITLE
fix(dynamic-elements): correctly apply scoping class to dynamic elements

### LINKED ISSUE #483: [Bug]: Tags nested inside dynamic tags don't get the scoping class
### Issue Category

Compilation Bug

### Bug Description

`<p>` doesn't get the scoping class here:
```html
<style>
  .my-class {
    p { color: red; }
  }
</style>
```
```tsx
let tag = track('div');
<@tag class="my-class"><p>{'Text'}</p></@tag>
```
But it does here:
```html
<div class="my-class"><p>{'Text'}</p></div>
```

### Reproduction Steps

[Playground](https://www.ripplejs.com/playground?v=0.2.129&title=Nested+selectors+%26+dynamic+tags#config=code%2FN4IgLglmA2CmIC4QDlYGcywCYAI2zgGMwB7AJzRwDIcsBPAOwEMBbCQnMJgczRABoQWdITIQADpBINEIASAAWsJllkAeFrC45CCphS0BeADogAqgBUAYgFoAHKZwB6AHzGGGrUxzNNJkABuELAA7uLkYI6E0pgMYP4hEFhgCobCQYSwNonJCvw4EAxQEEzQNmiEpbCGAIwAdAAMjq7yCmAs0ACCYGAUstBMDNz%2BsAxRA2ho-qbyXLyIANoAuoJMxBABsACiWFDkshVikvIs%2BgDWAK7iiKADQxc88EhtHfLRcaNg6ocSYJx04mqphYJCwFzgpjcY0gLHCZD%2BwBwIIucRwAF8cAAzMgkFg4ADkR3EcHxAG53MYYXC-gAqHBMSg-SRYnF40x1JxMsB1IkQkDksYMHA6aQYHCwAAe1MohhwAHkAEYAK1gxDqZ1gdDQAAouQBKAXC95izricQ4WWS6V1OBDFIWwyymoUyJgAD8eFEvwWVoiaAWDSWSxdlIQOF1XskdWEmKY4L%2BAB8E56jtzTeakynvb74Wg6pjClhtbALS5-oCSJis5IfUsHbL8ZiUetpPicHqlgb3MKIFXtWAAbBKzh0zgAISOglNhgthj4vU4YDd4WcBQ4kI%2BUI4LZkHFkbX45AkHABUpJcVSiJYkgorDzw3o5fIuLa9P5JdCldcMjcLRhrAkIQFyaHEdQKqCdB1EwZqjFgADCCgQNARYAUBIHcqIyiYFscDoQeuwBPOer8MuaJdh4nKRmALggGiggYHQcA3CAdzcA8v6yIQkxvDEnyyK0STCAwcG8XEsjgfQi7XnENixmw0B0GGNjQcSWRoFqmAsPkABC0CFGcACyawAMoabALBWDE%2BT4sZsDcCQJZmAAkvi%2BQAEokOBpD5HKEp0L%2BDD5GYCoomAFz5HBgzfgQ0DWXKgJCsZgxoK5BIABIEJskCVDgqAXLAqVoMl5SwGImKkjgCprGc3A4reYYKGg0Dag0%2BQNAApPkNR2O1BoitA5BhgAxJio3orR9FUcxrHsU8IC8vAgjvLEXxIBAsJXoivTVeiLK4gSC1khSDA5n8MZxtAfzRBtJ2oum2oLh%2BwpwH8cwWpwZDVfhGz3sdwrTrOnAkNw3BwBYPAPYuy7CgAAm9spwzw9YEgRbYevi4htmG%2BKow%2BaJ-TgaiI9wOgTFMwJ0DYhBk5CajiC4wAAAYWIhlAQJQ9C%2BOwnA8GGAAkwDE2ijNomoTj02LxNQsKagEaTDLkyALCU9TCu0-TTMs%2BzBSMlw2U89w-4bCLYsS04BHS4TIU9NIODSHBemEGchjAKQINgzwaIM-iFjA6DJZzPiotONbpAMFCy5qAxcCW8KdTK1TZNQ5%2BK44OaT2pyu0QDWQYZkNgD6p-jKePp%2BYvR7AUJohNIAV2gShaHwCDLJNqZNy3IBcWgAAK%2Bf4KtciCOIOKZJM5DtysncXBguK2T0hTzAgoALcxmwUBA0iyA0dQAEx1DUO8AJy0XRIDrdKNynwOgJN8AV-oGAt8sYMbGPLI18iKmPEfGJSA12vaAN4yCQAAFgAOyzBICQaAT9RhMAVHAVQSBSjQHkGsSAmxOKimgYtWuetp6yBIAlE%2BQA)

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox 143.0.3
- Ripple: 0.2.129
```

### Additional Context

_No response_

### Checklist

- [x] I've searched for existing issues
- [x] I'm willing to help implement a fix

### PR DESCRIPTION
**Pull request by Yusyuriv**
Closes #483.

Okay, I'm going to be honest. I just really wanted to fix the bug mentioned in the issue. I didn't really know what I was doing, I was just tinkering with the code until I got the desired behavior. It passes all existing tests, and I wrote a few new tests to cover the new behavior. However, I'd really like someone else to take a look at these changes to make sure there are no undesired side effects.

### CODE REVIEW

File: packages/ripple/src/compiler/phases/3-transform/client/index.js [hunk 1]
```diff
@@ -150,6 +150,19 @@ function visit_title_element(node, context) {
 	}
 }
 
+function mark_scoped_css_recursively(node) {
```
Comment (trueadm) [inline packages/ripple/src/compiler/phases/3-transform/client/index.js]: We never want to visit children, because the children might get replaced during the transformation process. Instead we just want to apply this during the Element visitor. We can look up the through the parents, and see if the component has `state.component.css` using `context.path`.

Comment (Yusyuriv) [reply packages/ripple/src/compiler/phases/3-transform/client/index.js]: Done. All tests still pass.

**Comment by trueadm** [comment]
Needs merge conflict fixes
