### PR TITLE
Fix svg namespace

### LINKED ISSUE #289: [Bug]: Dynamic svg elements don't work
### Issue Category

Behavioral Bug

### Bug Description

Dynamic svg doesn't work. Probably a namespace issue

### Reproduction Steps

https://ripplejs.com/playground#config=code%2FN4IgLglmA2CmIC4QFUB2kawCYAIAKATgPYBWsAxmCADQhawDO5BEADpEaoiDSABawAhlm4AeALawwgnOT6CCDKQF4AOigAqAMQC0ADnU4A9AD5VqCVJmpBktSABuEWAHdWRAmEPlOYWOnsXCCwwPmV6J3JYHSCQvmocCFQoCEFoHSY02GUARgA6AAZDU14%2BMHFoAEEwMEVuaEFUAHN7f28GhgZ7dV5pJoZEAG0AXVpBSggHWABRLCgPbiYWdl5xBQBrAFdWRFAG5s3BJvgkMoreH3R-KiQQAF9aBjAATzhdkH2mw%2BPuck6L3zXbgAIyIWGeOGAOAAZr4dNDbBBoM8EDgdIJWKw4Blnk9YOIEgAhaBJdYAWXGAGVcX5xFpfAkAOSU2BNIiwHDIACSjISACUiKCwEQEgB5AAez2OqASyGBm3QmwSAGFGtICLBoNAmaLWP4cJTGgxeThGQAJTVTSDkGQAOVgm1gJoYRoysBY0IA3DhgeN1k1iAqsKi%2BAxoAAKAoJAoAUgSOT0MYAlN6fNAPKiAMTQnM4O73R7MNg3PaNL5HE4gZZY%2BC0S5%2BdDcCDidyeSE4Wp%2BvMw4jiU3VuCMz3mEeoS5PHC4ZQ4QbqcQ5AAsOByACYcEuNzoF%2BoEuoyQnlwA2ABqAHYdzg52ucof14UAMwATh0j7yh8fgjyAFZvzgCn-lxwPJHxXe8-wAGRyHIjwvPd7zye8CiXHJ7z4Q8EJA9RhlHWBxVbMBJ1gBFNmgAifBbThrhwSpMXDJNIXMHAcFEOYHFkDounUetBCSd11DMVAmMYy9BOYhgHCaHBxQqVBOP4GpWAQIwjBcVS8hceCPCaIwVwKPSjHEppDFiUJ7BXbcQBwAQICaMozIsmEkWgexUEowwnmIdZsi4zYCA1dBlSIdMCHc2oiC8mJglM9QV1CzzohJVAKAxexA1QLA4vChLeJIIgklSogg344SmNhAgcHDccCNYQRQhwIhoUnejgBKpjmJquqsGUYAOr4O5jAEtq82E0QDIkwaRKY0RDJwDyssiuIzMMaToFk%2BwyjARTlNUlx1M0ghtN0-TDOMqKwhihzrNssB7MMJxXEJIhxXsf9-3MnBzMMaEnJctzLLmrz7HIXz-LAQLgsyiLEuS1gCqK-6wqhnK8tQOH0uK0Spt6yd7HnZC1w3dct340beomrHar4HG9wPG8zxJowyda0Rsa6q8jzvAonxfN8P2-X9XsA4DQIgqCYJAExScp8n2sp6mQDJeDEOQ1D0KfWKJal0IJtGwyBJGoxWP1zHzDucwCxAJ5XkYAQpAGBARkLZYwHtx2QD%2BBhCEYKRuF4VhiCiToPFd0Z3c2J4iHEFkaiSfp3gHE5QCmRQIE4bgCjyFc31Pe4HhAZt8Pt4A85ePUi5LxgXfeT5vkrUvGCLFY60BRtbjz5OGFTrgkAXQ9eiIIKi5AfxBGBOARCQNJoF4cZICmX5OAYILa0t6QwHD350yUEQ7juIA 

### Environment

```markdown

```

### Additional Context

_No response_

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

### PR DESCRIPTION
**Pull request by anubra266**
Fixes #289

### CODE REVIEW

File: packages/ripple/src/runtime/internal/client/template.js [hunk 1]
```diff
@@ -49,3 +53,87 @@ export function template(content, flags) {
 export function append(anchor, dom) {
   anchor.before(/** @type {Node} */ (dom));
 }
+
+const SVG_ELEMENTS = new Set([
```
Comment (trueadm) [inline packages/ripple/src/runtime/internal/client/template.js]: We don't want to be doing this during runtime, this should be something the compiler does using namespaces. See how Svelte does this:

https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/compiler/phases/3-transform/client/visitors/RegularElement.js#L292

https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/internal/client/dom/template.js#L91

Comment (anubra266) [reply packages/ripple/src/runtime/internal/client/template.js]: Thanks.. I had searched svelte codebase but couldn't find these 😁

**Comment by trueadm** [comment]
I think you need to rebase main

**Comment by anubra266** [comment]
Done @trueadm

File: packages/ripple/src/compiler/phases/3-transform/index.js [hunk 2]
```diff
@@ -427,6 +443,11 @@ const visitors = {
     const is_spreading = node.attributes.some((attr) => attr.type === 'SpreadAttribute');
     const spread_attributes = is_spreading ? [] : null;
 
+    const previous_namespace = state.namespace;
+    if (is_dom_element) {
+      state.namespace = determine_namespace_for_children(node.id.name, state.namespace);
```
Comment (trueadm) [inline packages/ripple/src/compiler/phases/3-transform/index.js]: We don't want to mutate state like this, but rather when we pass it to our children visitor we can pass it through, like Svelte does. This ensures that our children can have have a different value if they go out of svg into another namespace.

there's also mathml namespace too

**Comment by trueadm** [comment]
We also need to apply a different bit of logice for set_class, as with SVG you can't use `className`. I'm not sure if we use `setAttribute` or `setAttributeNS`

**Comment by anubra266** [comment]
Updated PR @trueadm. Going to bed it's 3am 😂 
I hope I fixed it all this time.

File: packages/ripple/src/runtime/internal/client/render.js [hunk 3]
```diff
@@ -134,7 +134,15 @@ export function set_class(dom, value, hash) {
     if (value == null && !hash) {
       dom.removeAttribute('class');
     } else {
-      dom.className = next_class_name;
+      // SVG and MathML elements don't support className property, must use setAttribute
+      if (
+        dom.namespaceURI === 'http://www.w3.org/2000/svg' ||
```
Comment (trueadm) [inline packages/ripple/src/runtime/internal/client/render.js]: we likely just want `is_html` to be passed in from the compiler based off the namespace, rather than doing these expensive lookups here

File: packages/ripple/src/compiler/phases/3-transform/index.js [hunk 4]
```diff
@@ -1430,6 +1458,31 @@ function transform_children(children, context) {
...
+        name === 'svg' ||
+        name === 'math' ||
+        (template_namespace === 'svg' && name !== 'foreignObject')
+      );
+    }
+    return false;
+  });
+
+  if (hasNamespaceElement) {
+    const firstElement = normalized.find(
```
Comment (trueadm) [inline packages/ripple/src/compiler/phases/3-transform/index.js]: We are we only checking the firstElement?

**Comment by trueadm** [comment]
Great work so far, nearly there!

File: packages/ripple/src/runtime/internal/client/template.js [hunk 5]
```diff
@@ -70,3 +89,28 @@ export function template(content, flags) {
 export function append(anchor, dom) {
   anchor.before(/** @type {Node} */ (dom));
 }
+
+const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
+const MATHML_NAMESPACE = 'http://www.w3.org/1998/Math/MathML';
+
+function create_svg_fragment_from_html(html) {
+  var svgContainer = document.createElementNS(SVG_NAMESPACE, 'svg');
```
Comment (trueadm) [inline packages/ripple/src/runtime/internal/client/template.js]: We can simplify this by simply wrapping the template in `svg` or `math`, this will force the namespace to be correct instead of doing it this way. See https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/internal/client/dom/template.js#L99

File: packages/ripple/src/runtime/internal/client/render.js (hunk 3 above)
Comment (anubra266) [reply packages/ripple/src/runtime/internal/client/render.js]: Makes sense. Thought we'd still do a run time check for spread props
https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/internal/client/dom/elements/attributes.js#L350

**Comment by trueadm** [comment]
Awesome work! Mind adding a `svg.test.ripple` module that validates the output and that the namespace of the `<svg>` and child node of that has the correct namespace? :)

**Comment by anubra266** [comment]
Done @trueadm

**Comment by trueadm** [comment]
I'd revert the cleanup, it looks like you applied our currently broken prettier formatter. Please could create any issues you find the the formater?

**Comment by anubra266** [comment]
Done @trueadm
