### PR TITLE
fix(cli): update Tailwind scaffolding to v4 CSS-first config

### LINKED ISSUE #843: [Bug]: Tailwindcss Intellisense not working
### Issue Category

Compilation Bug

### Bug Description

i tried configuring the tailwindCSS extension in with its language set to js, ts, js reactjs, reactts and html as well not work in any of them and @config in index.css shows error

### Reproduction Steps

**Reproduction Steps:**
1. Scaffold a new Ripple application using the standard create-ripple template.
2. Check the `package.json` — note that it installs Tailwind CSS **v4** (`"tailwindcss": "^4.x"` and `@tailwindcss/vite`).
3. Open `src/index.css` and observe the line: `@config "../tailwind.config.ts";`.
4. Boot up the dev server or open the project in an editor with the Tailwind CSS IntelliSense extension. 

**Expected Behavior:**
Tailwind compiles successfully and IntelliSense suggestions appear inside `.ripple` files. 

**Actual Behavior:**
1. The `@config` directive throws an error. This is because **Tailwind v4 explicitly dropped support for `.ts` files** in the `@config` directive. 
2. Because the TypeScript config file crashes the v4 parser, the Tailwind CSS Language Server (IntelliSense) silently crashes in the background, meaning autocomplete breaks for *all* files. 
3. Even if fixed, `.ripple` files aren't natively mapped to trigger IntelliSense.

### Environment

```markdown

```

### Additional Context

_No response_

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

### PR DESCRIPTION
**Pull request by RazinShafayet2007**
Fixes #843

### Problem

When scaffolding a new Ripple project with the TailwindCSS option, the CLI generates a v3-style setup that breaks under Tailwind v4:

1. **`tailwind.config.ts`** — Tailwind v4 dropped `.ts` support in the `@config` directive
2. **`@config "../tailwind.config.ts"`** in `index.css` — crashes the Tailwind v4 parser, which silently kills the Tailwind CSS Language Server (IntelliSense)
3. **`.ripple` files** aren't mapped in VS Code settings, so IntelliSense never triggers in Ripple components even if Tailwind compiles

### Fix

- **Removed** `tailwind.config.ts` generation — v4 uses CSS-first config and auto-detects content sources
- **Removed** `@config` directive — `index.css` now only contains `@import "tailwindcss";`
- **Added** `.vscode/settings.json` generation with `tailwindCSS.includeLanguages: { ripple: "html" }` so IntelliSense works in `.ripple` files

### Changed Files

- `packages/cli/src/lib/project-creator.js` — updated `configureStyling()` function
- `packages/cli/tests/integration/project-creator.test.js` — updated Tailwind test assertions

### Testing

All 71 CLI tests pass (`pnpm test --project cli`).

---

> [!NOTE]
> **Low Risk**
> Low risk: changes are limited to CLI project scaffolding for Tailwind and corresponding integration test updates, with no runtime app logic or security-sensitive behavior affected.
> 
> **Overview**
> Updates `create-ripple` Tailwind scaffolding to match Tailwind v4’s *CSS-first* setup by **stopping generation of `tailwind.config.ts`** and **removing the `@config` directive** from the generated `src/index.css` (now only `@import "tailwindcss";`).
> 
> Also **generates `.vscode/settings.json`** to enable Tailwind IntelliSense in `*.ripple` files, and updates the Tailwind integration test to assert the new outputs. A changeset publishes this as a patch for `@ripple-ts/cli`.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 6eaf590ed01ecc5ab845e6ce7752e226f6454411. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: packages/cli/src/lib/project-creator.js [hunk 1]
```diff
@@ -240,13 +228,27 @@ import { ripple } from '@ripple-ts/vite-plugin';
 import tailwindcss from '@tailwindcss/vite';
 
 export default defineConfig({
-	plugins: [ripple(), tailwindcss()],
-	server: {
-		port: 3000
-	}
+\tplugins: [ripple(), tailwindcss()],
```
Comment (trueadm) [inline packages/cli/src/lib/project-creator.js]: What's with the changes here?

Comment (RazinShafayet2007) [reply packages/cli/src/lib/project-creator.js]: Ah, my bad. Opus accidentally injected literal `\t` escape characters into the template literal instead of proper tab indentation. Fixing it!

**Review by trueadm — APPROVED** [review]
Thank you
