### PR TITLE
fix missing prop descriptors

### LINKED ISSUE #448: [Bug]: Getting compilation error when using @tracked_var inside ts file
### Issue Category

Compilation Bug

### Bug Description

I come across this scenario when I created a `.ts` store file and using effect it gives compilation error

```jsx 
import { effect, track } from "ripple"

// countStore.ts
export function useCount() {
  const count = track(1)
  effect(() => {
    console.log(@count)
  })
  return { count }
}

```

```jsx
import { useCount } from './countStore'; //using countStore.ts
import { effect } from "ripple"

export component App() {
  const { count } = useCount()
  effect(() => {
   const id = setInterval(() => {
      @count++;
    }, 1000);

    return () => clearInterval(id)
  })
  <h1>{@count}</h1>
}
```

getting compilation error
```bash
[plugin:vite:esbuild] Transform failed with 1 error:
C:/Workspace/my-ripple-app/src/countStore.ts:7:22: ERROR: Expected "class" but found ")"
```

### Reproduction Steps

1. create a sample app using latest ripple version
2. create countStore.ts and copy the copy
3. update App.ripple and copy App component code

### Environment

```markdown
- latest ripple version
```

### Additional Context

But when I used `.ripple` file as store it works, like below
```jsx
import { effect, track } from "ripple"

// countStore.ripple
export function useCount() {
  const count = track(1)
  effect(() => {
    console.log(@count)
  })
  return { count }
}

```
```jsx
import { useCount } from './countStore.ripple';
import { effect } from "ripple"

export component App() {
  const { count } = useCount()
  effect(() => {
   const id = setInterval(() => {
      @count++;
    }, 1000);

    return () => clearInterval(id)
  })
  <h1>{@count}</h1>
}
```

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

### PR DESCRIPTION
**Pull request by leonidaz**
fixes #448 

- We need to get the actual descriptors otherwise we lose the getters.

### CODE REVIEW

File: packages/ripple/src/runtime/internal/client/runtime.js [hunk 1]
```diff
@@ -922,11 +922,7 @@ export function spread_props(fn, block) {
 				const obj = get_derived(computed);
 
 				if (key in obj) {
-					return {
-						enumerable: true,
-						configurable: true,
-						value: obj[key],
-					};
+					return Object.getOwnPropertyDescriptor(obj, key);
```
Comment (trueadm) [inline packages/ripple/src/runtime/internal/client/runtime.js]: We have an import we can use instead of doing this “own_property_descriptor”

**Review by trueadm — APPROVED** [review]
